use crate::agent::{AgentPlan, PlanStep};
use std::collections::VecDeque;

/// A simple queue manager to hold steps dynamically for the ORGA cycle
pub struct TodoManager {
    queue: VecDeque<PlanStep>,
}

impl TodoManager {
    pub fn new() -> Self {
        Self {
            queue: VecDeque::new(),
        }
    }

    /// Add a new batch of steps generated by the planner
    pub fn push_plan(&mut self, plan: AgentPlan) {
        for step in plan.steps {
            self.queue.push_back(step);
        }
    }

    /// Pull the next step to execute
    pub fn next_step(&mut self) -> Option<PlanStep> {
        self.queue.pop_front()
    }

    /// Prune remaining steps if the evaluator deems the current path a failure (Sunk Cost Immunity)
    pub fn prune(&mut self) {
        self.queue.clear();
    }

    pub fn is_empty(&self) -> bool {
        self.queue.is_empty()
    }
}
