//! Report Generator — converts research findings into formatted reports

use omniscient_core::types::ResearchReport;

/// Generates formatted reports from research results
pub struct ReportGenerator;

impl ReportGenerator {
    pub fn new() -> Self {
        Self
    }

    /// Generate a markdown report from research results
    pub fn generate_markdown(&self, report: &ResearchReport) -> String {
        let mut md = String::new();

        // Title
        md.push_str(&format!("# {}\n\n", report.title));

        // Metadata
        md.push_str(&format!(
            "> **Query**: {}\n>\n> **Generated**: {}\n>\n> **Depth**: {:?}\n>\n> **Sources Consulted**: {}\n\n",
            report.query,
            report.generated_at.format("%Y-%m-%d %H:%M UTC"),
            report.research_depth,
            report.total_sources_consulted,
        ));

        md.push_str("---\n\n");

        // Executive Summary
        md.push_str("## Executive Summary\n\n");
        md.push_str(&report.executive_summary);
        md.push_str("\n\n");

        // Sections
        for section in &report.sections {
            md.push_str(&format!("## {}\n\n", section.title));
            md.push_str(&section.content);
            md.push_str("\n\n");

            for subsection in &section.subsections {
                md.push_str(&format!("### {}\n\n", subsection.title));
                md.push_str(&subsection.content);
                md.push_str("\n\n");
            }
        }

        // Key Findings
        if !report.findings.is_empty() {
            md.push_str("## Key Findings\n\n");
            for (i, finding) in report.findings.iter().enumerate() {
                md.push_str(&format!(
                    "{}. **[{:?}]** {} *(Confidence: {:.0}%)*\n",
                    i + 1,
                    finding.category,
                    finding.content,
                    finding.confidence * 100.0,
                ));
            }
            md.push_str("\n");
        }

        // Entities
        if !report.entities.is_empty() {
            md.push_str("## Entities Discovered\n\n");
            md.push_str("| Entity | Type | Details |\n");
            md.push_str("|--------|------|--------|\n");
            for entity in &report.entities {
                md.push_str(&format!(
                    "| {} | {:?} | {} |\n",
                    entity.name, entity.entity_type, entity.attributes
                ));
            }
            md.push_str("\n");
        }

        // Sources
        if !report.sources.is_empty() {
            md.push_str("## Sources\n\n");
            for (i, source) in report.sources.iter().enumerate() {
                let url_str = source
                    .url
                    .as_ref()
                    .map(|u| format!(" — [Link]({})", u))
                    .unwrap_or_default();
                md.push_str(&format!(
                    "{}. **{}**{} *(Reliability: {:.0}%)*\n",
                    i + 1,
                    source.title,
                    url_str,
                    source.reliability_score * 100.0,
                ));
            }
        }

        // Footer
        md.push_str("\n---\n\n");
        md.push_str("*Generated by Omniscient — The God of All Research Agents*\n");

        md
    }

    /// Save report to file
    pub fn save(&self, report: &ResearchReport, path: &std::path::Path) -> std::io::Result<()> {
        let markdown = self.generate_markdown(report);
        std::fs::write(path, markdown)
    }
}

impl Default for ReportGenerator {
    fn default() -> Self {
        Self::new()
    }
}
